version: "3.9"

services:
  mongodb:
    image: mongo:7.0
    container_name: bughunter_mongodb
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
    container_name: bughunter_backend
    env_file:
      - ./backend/.env          
    volumes:
      - ./backend/app:/code/app
      - ./backend/.env:/code/.env  
    ports:
      - "8000:8000"
    depends_on:
      - mongodb


  frontend:
    build:
      context: ./frontend
    container_name: bughunter_frontend

    volumes:
      - ./frontend/app:/code/app               
    ports:
      - "5173:5173"
    depends_on:
      - backend


volumes:
  mongo-data:
