name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v4

      - name: Setup a local virtual environment
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - name: Cache Poetry virtual environment
        uses: actions/cache@v4
        with:
          path: backend/.venv
          key: ${{ runner.os }}-backend-venv-${{ hashFiles('backend/**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-backend-venv-

      - name: Install dependencies
        run: poetry install

      - name: Lint with Ruff
        run: poetry run ruff linter
